# Pytorch: Warm-up

In [1]:
from __future__ import print_function
import numpy as np
import torch
SEED=123
np.random.seed(SEED)
torch.manual_seed(SEED)
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
torch.ones(size=(3,2));
torch.zeros(size=(3,6));

## Dataloader

In [20]:

class dataset:
    
    def __init__(self):
        self._data = tuple(range(100))
        
    def __len__(self):
        return len(self._data)
    
    def __getitem__(self,index):
        return self._data[index]
    
data = dataset()

In [22]:

from torch.utils.data import DataLoader
loader = DataLoader(data,batch_size=10,shuffle=True,num_workers=0)
ctr = 0
while ctr<20:
    for batch_data in loader:
        print('Iteration',ctr,'batch data',batch_data)
        ctr += 1

Iteration 0 batch data tensor([79, 33, 92, 60, 68, 35, 12, 70, 94, 98])
Iteration 1 batch data tensor([20, 65, 46,  3, 43, 19, 78, 44, 41, 69])
Iteration 2 batch data tensor([95, 36, 39,  2, 90, 55, 52, 40, 11, 74])
Iteration 3 batch data tensor([31, 34, 71, 61, 84, 88, 49, 28, 96, 85])
Iteration 4 batch data tensor([51, 25, 81,  9,  7, 57, 22, 53, 32, 64])
Iteration 5 batch data tensor([76, 13,  5, 29, 26, 14, 82, 15,  6, 66])
Iteration 6 batch data tensor([47, 86, 30, 75, 23, 87, 42, 54, 10,  8])
Iteration 7 batch data tensor([50, 93, 38, 83, 24, 56, 99, 91, 59, 37])
Iteration 8 batch data tensor([16,  1, 89, 48, 80,  4, 67, 58, 97, 21])
Iteration 9 batch data tensor([72, 63, 62, 77, 73, 17, 45, 18, 27,  0])
Iteration 10 batch data tensor([51, 16, 97, 85, 58, 80, 22, 64, 61, 44])
Iteration 11 batch data tensor([83, 66, 60, 79, 99, 89, 90,  3, 65, 48])
Iteration 12 batch data tensor([ 6, 91, 75, 63, 14,  1, 70, 35, 41, 73])
Iteration 13 batch data tensor([42, 43,  0, 34, 49, 17, 32, 7

In [23]:
# Create a 2D tensor of shape (1,5,5) with some negative and positive values
torch.manual_seed(123)
data = torch.randn(60).reshape(2,5,6)
data

tensor([[[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603],
         [-0.2196, -0.3792,  0.7671, -1.1925,  0.6984, -1.4097],
         [ 0.1794,  1.8951,  0.4954,  0.2692, -0.0770, -1.0205],
         [-0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
         [ 0.4965, -1.5723,  0.9666, -1.1481, -1.1589,  0.3255]],

        [[-0.6315, -2.8400, -1.3250,  0.1784, -2.1338,  1.0524],
         [-0.3885, -0.9343, -0.4991, -1.0867,  0.8805,  1.5542],
         [ 0.6266, -0.1755,  1.3111, -0.2199,  0.2190,  0.2045],
         [ 0.5146,  0.9938, -0.2587, -1.0826,  0.1036, -2.1996],
         [-0.0885, -0.5612,  0.6716,  0.6933, -0.9487, -0.0765]]])

In [48]:
torch.manual_seed(123)

# Implement steps 1 to 5
op1 = torch.nn.ReLU()
op2 = torch.nn.Softmax(dim=2)
op3 = torch.nn.MaxPool2d(kernel_size=(1,3))

op1r = op1(data)
print(op1r)
op2r = op2(op1r)
print(op2r)
op3r = op3(op2r)
print(op3r)
flattened = torch.flatten(op3(op2(op1(data))))
#print('Shape of the output after flatten', flattened.shape)



tensor([[[0.3374, 0.0000, 0.0000, 0.0000, 0.3486, 0.6603],
         [0.0000, 0.0000, 0.7671, 0.0000, 0.6984, 0.0000],
         [0.1794, 1.8951, 0.4954, 0.2692, 0.0000, 0.0000],
         [0.0000, 0.9178, 1.5810, 1.3010, 1.2753, 0.0000],
         [0.4965, 0.0000, 0.9666, 0.0000, 0.0000, 0.3255]],

        [[0.0000, 0.0000, 0.0000, 0.1784, 0.0000, 1.0524],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.8805, 1.5542],
         [0.6266, 0.0000, 1.3111, 0.0000, 0.2190, 0.2045],
         [0.5146, 0.9938, 0.0000, 0.0000, 0.1036, 0.0000],
         [0.0000, 0.0000, 0.6716, 0.6933, 0.0000, 0.0000]]])
tensor([[[0.1807, 0.1290, 0.1290, 0.1290, 0.1828, 0.2496],
         [0.1225, 0.1225, 0.2638, 0.1225, 0.2463, 0.1225],
         [0.0935, 0.5198, 0.1282, 0.1023, 0.0781, 0.0781],
         [0.0602, 0.1507, 0.2925, 0.2211, 0.2154, 0.0602],
         [0.1898, 0.1155, 0.3037, 0.1155, 0.1155, 0.1600]],

        [[0.1241, 0.1241, 0.1241, 0.1483, 0.1241, 0.3554],
         [0.0897, 0.0897, 0.0897, 0.0897, 0.2165, 

RuntimeError: Boolean value of Tensor with more than one value is ambiguous